name: Test workflow

on: [push]

env:
  # TODO(@wchargin): Parameterize.
  BAZEL: "0.26.1"
  BAZEL_SHA256SUM: "6c50e142a0a405d3d8598050d6c1b3920c8cdb82a7ffca6fc067cb474275148f"
  TF_VERSION_ID: "tensorflow==1.15.0rc3"

jobs:
  build:
    runs-on: ubuntu-16.04
    steps:
      - name: "Check out repository"
        uses: actions/checkout@v1
      - name: "Set up Python"
        uses: actions/setup-python@v1
        with:
          python-version: "3.6"
          architecture: "x64"

      - name: "Set up Bazel"
        run: |
          ci/download_bazel.sh "${BAZEL}" "${BAZEL_SHA256SUM}" ~/bazel
          sudo mv ~/bazel /usr/local/bin/bazel
          cp ./ci/bazelrc ~/.bazelrc

      - name: "Install Python dependencies"
        run: |
          python -m pip install -U pip
          pip install -r ./ci/requirements.txt -r ./ci/requirements_dev.txt
          pip uninstall -y numpy
          # Workaround for https://github.com/travis-ci/travis-ci/issues/7940
          sudo rm -f /etc/boto.cfg

      - name: "Install TensorFlow"
        run: pip install "${TF_VERSION_ID}"

      - name: "Set up Angular"
        run: yarn install --ignore-engines

      - name: "Check Pip state"
        run: pip freeze --all

      - name: "Check existing /etc/hosts"
        run: cat /etc/hosts

      - run: python ./tensorboard/tools/diagnose_tensorboard.py

      - name: "Lint for Python"
        run: flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics

      - name: "Bazel: Fetch all dependencies"
        run: bazel fetch //tensorboard/...
      - name: "Check cache size after fetch"
        run: |
          du -sh ~/.cache/tb-bazel-repo || true

      - name: "Run smoke test"
        run: bazel test //tensorboard/examples/plugins/example_basic:smoke_test

      - name: "Run Pip package test"
        run: bazel run //tensorboard/pip_package:test_pip_package -- --default-python-only --tf-version "${TF_VERSION_ID}"

      - name: "Bazel: Build all targets"
        run: bazel build //tensorboard/...
      - name: "Check cache size after build"
        run: |
          du -sh ~/.cache/tb-bazel-repo || true

      - name: "Bazel: Run tests, skipping web tests"
        run: bazel test //tensorboard/... --test_tag_filters=-webtest
      - name: "Check cache size after first round of tests"
        run: |
          du -sh ~/.cache/tb-bazel-repo || true

      - name: "Bazel: Run web tests"
        run: bazel test //tensorboard/... --test_tag_filters=webtest
      - name: "Check cache size after second round of tests"
        run: |
          du -sh ~/.cache/tb-bazel-repo || true

# vim: sw=2 ts=2 sts=2
